language: python
python: 2.7
# command to install dependencies
install:
  - pip install tox
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=pep8
script:
  - tox -e $TOX_ENV